{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-admin-credentials" (include "kubex-operator.fullname" .))) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubex-operator.fullname" . }}-admin-credentials
  labels:
    {{- include "kubex-operator.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ "kubex-admin" | b64enc | quote }}
  {{- if $existingSecret }}
  password: {{ index $existingSecret.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
