apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubex-operator.fullname" . }}-api
  labels:
    {{- include "kubex-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api-ui
      protocol: TCP
      name: http
  selector:
    {{- include "kubex-operator.selectorLabels" . | nindent 4 }}
