# This rule is not used by the project kubex itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the finops.kubex.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubex
    app.kubernetes.io/managed-by: kustomize
  name: scalinggroup-editor-role
rules:
- apiGroups:
  - finops.kubex.io
  resources:
  - scalinggroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finops.kubex.io
  resources:
  - scalinggroups/status
  verbs:
  - get
